product_project_folder/cinemaproject/cinemaapp/urls.py
from django.urls import path
from . import views
app_name='cinemaapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('cinema/<int:cinema_id>/',views.detail,name='detail'),
    path('add/',views.add_cinema,name='add_cinema'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

product_project_folder/cinemaproject/cinemaproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("cinemaapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product_project_folder/cinemaproject/cinemaapp/models.py
from django.db import models

# Create your models here.
class Cinema(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallary')

    def __str__(self):
        return self.name

product_project_folder/cinemaproject/cinemaapp/forms.py
from django import forms
from .models import Cinema

class  Cinemaforms(forms.ModelForm):
    class Meta:
        model=Cinema
        fields=['name','desc','year','img']

product_project_folder/cinemaproject/cinemaapp/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render, redirect
from . models import Cinema
from .forms import Cinemaforms




# Create your views here.
def index(request):
    cinema=Cinema.objects.all()
    context={
        'cinema_list':cinema
    }
    return render(request,'index.html',context)
def detail(request,cinema_id):
    cinema=Cinema.objects.get(id=cinema_id)

    return render(request,"detail.html",{'cinema':cinema})
def add_cinema(request):
    name = request.POST.get('name',)
    desc = request.POST.get('desc',)
    year = request.POST.get('year',)
    img  = request.FILES.get('img',)
    cinema=Cinema(name=name,desc=desc,year=year,img=img)
    if name:
        cinema = Cinema(name=name, desc=desc, year=year, img=img)
        cinema.save()
        return redirect('/')
    else:
        error_message = "Please provide a name for the cinema."
        context = {'error_message': error_message}
        return render(request, 'add.html', context)


    return render(request,'add.html')

def update(request,id):
    cinema=Cinema.objects.get(id=id)
    form=Cinemaforms(request.POST or None, request.FILES,instance=cinema)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'cinema':cinema})
def delete(request,id):
    if request.method=='POST':
        cinema=Cinema.objects.get(id=id)
        cinema.delete()
        return redirect('/')
    return render(request,'delete.html')

product_project_folder/cinemaproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
     <input type="text" name="name" placeholder="Enter your cinema name">
     <input type="text" name="desc" placeholder="Enter your movie description">
     <input type="text" name="year" placeholder="Enter your movie year">
     <input type="file" name="img" >
     <input type="submit">




</form>
{% endblock %}

product_project_folder/cinemaproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
        body {
            background-image: url('https://img.freepik.com/free-vector/network-mesh-wire-digital-technology-background_1017-27428.jpg?w=1380&t=st=1689602824~exp=1689603424~hmac=ea98fceeb0cb2d62631de9181219f725087f4c3844fa8d8382ada2a7a4972f9f');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    cinema
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

product_project_folder/cinemaproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Do you want to delete?
    <input type="submit">
</form>

product_project_folder/cinemaproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container" style="background-image: url('https://img.freepik.com/free-photo/abstract-digital-grid-black-background_53876-97647.jpg?w=1060&t=st=1689603551~exp=1689604151~hmac=5cd29e060122022d7ef41b1c8b39da7dd57be3571ea4b82055566a62218099d0'); background-size: cover; background-repeat: no-repeat; min-height: 100vh; display: flex; align-items: center;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ cinema.img.url }}" width="100" height="300">
        </div>
        <div class="col-md-6">
            <h6>{{ cinema.name }}</h6>
            <h6>{{ cinema.desc }}</h6>
            <h4>{{ cinema.year }}</h4>
            <a class="btn btn-warning" href="{% url 'cinemaapp:update' cinema.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'cinemaapp:delete' cinema.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

product_project_folder/cinemaproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

product_project_folder/cinemaproject/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in cinema_list %}
        <div class="col-md-3">
            <div class="card h-100">
                <img src="{{i.img.url}}" class="card-img-top" alt="" height="200px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a class="btn btn-warning" href="{% url 'cinemaapp:detail' i.id %}">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}